# Generated by Django 3.1.3 on 2020-11-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toping',
            new_name='Topping',
        ),
    ]
