# Generated by Django 3.1.3 on 2020-12-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_pizza_thumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
